bot:
  name: world_of_hack_bot
  token: 5118156282:AAFf_26NRcE2g9ke4nmv5g4kdzIl1Rs1OAY
  channel_id: -1001426146281
  channel_url: https://t.me/+N-Adwu4fCeA3ZGVi
  channel2_id: -1001697714908
  channel2_url: https://t.me/+suMJ2igZQIM2MTMy